#!/bin/sh

# This is intended to work in tandem with create_build_machine.sh to trigger nightly docker builds

SUDOWRT_DIR='/opt/sudowrt-firmware'

cd ${SUDOWRT_DIR}

rm -r ./firmware_images
git pull
# docker rm $(docker ps -a -q)
# docker rmi $(docker images -q) 
docker build -t sudomesh/sudowrt-firmware .
docker run -v $PWD/firmware_images:/firmware_images sudomesh/sudowrt-firmware

