#!/bin/bash
#
#  Intended to prepare an openwrt toolchain for building sudowrt firmware
#  Prepares openwrt builder. 
#
#  If you only want to build the firmware use [build].
#  If you only want to build the firmware, and delete the firmware binaries use [build_clean]
#

source build_lib

openwrt_clone_and_patch

validate_architecture $architecture

echo "Generating build configurations for [${architecture}]..."
openwrt_build_configure "${architecture}"
echo "Generating build configurations for [${architecture}] done."

echo "Preparing for build for [${architecture}]..."
openwrt_buildprep "${architecture}"
echo "Preparing for build for [${architecture}] done."
