#!/bin/bash
#
#  Intended to build a clean image for rebuilding sudowrt firmware
#  Prepares openwrt builder, builds sudowrt firmware, and then deletes the firmware binaries. 
#
#  If you only want to get *some* of the resources for building the firmware, use [build_pre]
#  If you only want to build the firmware and not delete the binaries, use [build].
#

source build_lib

openwrt_clone_and_patch

validate_architecture $architecture

echo "Generating build configurations for [${architecture}]..."
openwrt_build_configure "${architecture}"
echo "Generating build configurations for [${architecture}] done."

echo "Preparing for build for [${architecture}]..."
openwrt_buildprep "${architecture}"
echo "Preparing for build for [${architecture}] done."

echo "Building firmware for [${architecture}]..."
openwrt_builder "${architecture}"
echo "Building firmware for [${architecture}] done."

echo "Removing images for [${architecture}], just leaving builder..." 
remove_images "./bin/${architecture}"
echo "Removing images for [${architecture}] done."

