#!/bin/bash
#
#  Prepares and builds sudowrt-firmware. 
#
#  If you only want to build, use [build_only]. If you only want to get resources needed to build, use [build_pre].
#
source build_only
source build_pre

