#!/bin/bash
#
#  Builds sudowrt-firmware. Assumes that build_pre has successfully run.
#

source build_lib

echo "Building firmware for [${architecture}]..."
openwrt_builder "${architecture}"
echo "Building firmware for [${architecture}] done."
