#!/bin/bash
#
#  Builds sudowrt-firmware. Assumes that build_pre has successfully ran.
#

source build_lib

validate_architecture $architecture

echo "Building firmware for [${architecture}]..."
openwrt_builder "${architecture}"
echo "Building firmware for [${architecture}] done."
