#!/bin/bash
#
# Retrieves and configures resources needed for a build of sudowrt firmware.
#
# uses build_lib for build functions
#

# peopleswifi firmware prepare script
# based on wlanslovenija prepare script

source build_lib

openwrt_clone_and_patch

validate_architecture $architecture

echo "Generating build configurations for [${architecture}]..."
openwrt_build_configure "${architecture}"
echo "Generating build configurations for [${architecture}] done."

echo "Preparing for build for [${architecture}]..."
openwrt_buildprep "${architecture}"
echo "Preparing for build for [${architecture}] done."

echo "Building firmware for [${architecture}]..."
openwrt_builder "${architecture}"
echo "Building firmware for [${architecture}] done."

echo "Removing images for [${architecture}], just leaving builder..." 
remove_images "./bin/${architecture}"
echo "Removing images for [${architecture}] done."
