#!/bin/bash

# peopleswifi firmware prepare script
# based on wlanslovenija prepare script


BUILD_DIR=built_firmware

#echo "Checking dependencies"
#if [ ! command -v quilt ]; then
#  echo "quilt not found."
#  exit 1
#fi

echo "Checking working directory"
if [[ ! -d openwrt_config ]]; then
  echo "Invalid working directory!"
  exit 1
fi

workdir=$(pwd)
mkdir -p ${BUILD_DIR}

# Get version identifier
firmware_version=$(git describe --always)

openwrt_version=$(cat openwrt_config/version)
openwrt_path=$(echo $openwrt_version | cut -d ':' -f 1)
openwrt_path_name="${openwrt_path//\//-}"
openwrt_path_name="${openwrt_path_name//_/-}"
openwrt_rev=$(echo $openwrt_version | cut -d ':' -f 2)

echo "OpenWRT path: ${openwrt_path}"
echo "OpenWRT revision: ${openwrt_rev}"
echo "Checking out OpenWRT into ${BUILD_DIR}, this could take some time"

OPENWRT_CHECKOUT_DIR=${workdir}/${BUILD_DIR}/openwrt
if [ -f ${OPENWRT_CHECKOUT_DIR}/.success ]; then
  echo "OpenWRT already checked out"
else
  svn status ${OPENWRT_CHECKOUT_DIR}
  rm -rf ${OPENWRT_CHECKOUT_DIR}
  svn co -q -r ${openwrt_rev} svn://svn.openwrt.org/openwrt/${openwrt_path} ${OPENWRT_CHECKOUT_DIR}
  if [ $? -ne 0 ]; then
    echo "Error during svn checkout of OpenWRT"
    exit $?
  else
    # make a file indicating that this is a successfully checked out openwrt dir
    touch ${OPENWRT_CHECKOUT_DIR}/.success
  fi
  echo "Purging .svn files from repository"
  find ${OPENWRT_CHECKOUT_DIR} -name .svn -type d -exec rm -rf "{}" \; 2>/dev/null
fi


#echo "Applying patches for OpenWRT base tree..."

#ln -s ${workdir}/openwrt/patches/${openwrt_path_name} patches
#quilt push -f -a

# Inject feeds and configurations
echo "Configuring feeds"

all_feeds=$(cat ${workdir}/openwrt_config/feeds)
feed_titles=()
feed_sources=()
for feedline in ${all_feeds}; do
  IFS=: read -a ARRAY <<< "$feedline" # one-line solution
  feed_titles+=(ARRAY[0])

  SAVE_IFS=$IFS
  IFS=":"
  feed_source="${ARRAY[*]:1}"
  IFS=$SAVE_IFS

  feed_sources+=(feed_source)
done

for feed_source in ${feed_sources}; do
  echo "${feed_source}"  > ${OPENWRT_CHECKOUT_DIR}/feeds.conf    
done

echo "Changing work directory to openwrt"
cd ${OPENWRT_CHECKOUT_DIR}

# Importing feeds
echo "Importing feeds"
./scripts/feeds update -a > /dev/null

for feed_title in ${feed_titles}; do
  ./scripts/feeds install ${feed_title}
done

# change back to initial directory
cd ${workdir}

override_architectures="$*"

# Check architectures that we need to build
all_architectures=$(cat openwrt_config/architectures)
if [ -z "${override_architectures}" ]; then
  architectures="${all_architectures}"
else
  architectures=""
  for arch in $override_architectures; do
    found=0
    for sarch in $all_architectures; do
      if [[ "$arch" == "$sarch" ]]; then
        architectures="${architectures} ${arch}"
        found=1
        break
      fi
    done

    if [[ $found == 0 ]]; then
      echo "ERROR: Invalid architecture '${arch}' specified."
      exit 1
    fi
  done
fi

openwrt_verify_architecture()
{
  local arch=$1
  if [ ! -d ${workdir}/${BUILD_DIR}/openwrt/target/linux/${arch} ]; then
    echo "Invalid architecture '${arch}', aborting."
    exit 1
  fi

  if [ ! -f ${workdir}/openwrt_config/arch_configs/${arch} ]; then
    echo "Architecture '${arch}' missing configuration file, aborting."
    exit 1
  fi
}

echo "Configuring for the following OpenWRT architectures:"
for arch in $architectures; do
  openwrt_verify_architecture $arch
  echo " * ${arch}"
done


# Check packages that we need to build
echo "Configuring build for the following OpenWRT packages:"
all_packages=$(grep 'Package:' ${workdir}/${BUILD_DIR}/openwrt/feeds/peopleswifi.index | cut -d ':' -f 2)
all_packages="${all_packages} $(cat openwrt_config/packages)"
for pkg in $all_packages; do
  echo " * ${pkg}"
done

#echo "Cleaning up previous builder leftovers..."
#rm -rf ${workdir}/${BUILD_DIR}/builder.*
#rm -rf ${workdir}/${BUILD_DIR}/release


openwrt_build_configure()
{
  local arch=$1
  local kconfig=${workdir}/${BUILD_DIR}/openwrt/scripts/kconfig.pl
  local config_dir=${workdir}/openwrt_config/arch_configs
  local config=${workdir}/${BUILD_DIR}/openwrt/config.${arch}
  $kconfig 'm+' ${config_dir}/generic ${config_dir}/${arch} > ${config}

  # Include all common packages
  for pkg in ${all_packages}; do
    echo "CONFIG_PACKAGE_${pkg}=y" >> ${config}
  done

  # Remove configuration file already present in the generic build dir
  rm -f ${workdir}/${BUILD_DIR}/openwrt/.config
}

# Generate build configurations
echo "Generating build configurations..."
for arch in $architectures; do
  openwrt_build_configure $arch
done


openwrt_buildprep()
{
  local arch=$1
  local build_dir=${workdir}/${BUILD_DIR}/builder.${arch}.$$

  # Make hardlinks to avoid space duplication but to still isolate builds
  cp -lr ${workdir}/${BUILD_DIR}/openwrt ${build_dir}
  
  cp -r files ${build_dir}/
  
  # Prepare configuration file and build
  cd ${build_dir}
  cp config.${arch} .config
  make defconfig &> ${build_dir}/build.echo
  if [ "$?" != "0" ]; then
    echo "Default configuration preparation for '${arch}' has failed. See build.echo for details!"
    exit 1
  fi

  echo "Installing tools"
  make tools/install
  make toolchain/install

  echo "Compile linux"
  make target/compile 
  
  echo "Compiling packages"
  make package/cleanup
  make package/compile

  echo "Installing packages"
  make package/install

}

echo "Configure for build."
for arch in $architectures; do
  openwrt_build_configure $arch
done

echo "Prepare for build"
for arch in $architectures; do
  openwrt_buildprep ${arch}
done

# Preparation is now completed
echo "Preparation completed, you may now build the firmware or build single packages."
