#!/bin/sh 
# This script retrieves an IP address
# from a meshnode-database, running some version of
# https://github.com/sudomesh/meshnode-database
# Once an IP is retrieved, this script triggers 
# the configuration of this node with the correct
# MESH IP and other related settings stored in
# /opt/mesh/zeroconf

# import json parser
. /usr/share/libubox/jshn.sh

# default configs for People's Open Network
LOG="/var/log/retrieve_ip.log"
MESHNODEDB="secrets.peoplesopen.net"
MESHNODEDB_IP="138.68.252.190"
USER="deployer"
PASS="praisebob"
POSTURL="https://$USER:$PASS@$MESHNODEDB/nodes"

echo "retrieving an IP address from" $MESHNODEDB >>$LOG

# check for internet connection for every every 10s 
for i in 1 2 3 4 5;
do
  if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
    echo "IPv4 is up" >>$LOG
    break
  else
    echo "IPv4 is down" >>$LOG
  fi
  sleep 10
done

if ping -q -c 1 -W 1 google.com >/dev/null; then
  echo "DNS is working" >>$LOG
else
  echo "DNS is not working" >>$LOG
  exit 1
fi

if ping -q -c 1 -W 1 $MESHNODEDB >/dev/null; then
  echo $MESHNODEDB "is reachable" >>$LOG
else
  echo $MESHNODEDB "is not reachable" >>$LOG
  echo "trying by IP" $MESHNODEDB_IP >>$LOG
  if ping -q -c 1 -W 1  $MESHNODEDB_IP >/dev/null; then
    echo $MESHNODEDB_IP "is reachable" >>$LOG
  else
    echo $MESHNODEDB_IP "is not reachable" >>$LOG
    exit 1
  fi
fi

# make a post request to meshnode-databse
echo "posting to" $POSTURL >>$LOG
MESHNODE_DATA=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode data='{"type":"node"}' $POSTURL )

# parse the json response
json_load "$MESHNODE_DATA"
json_select data 
json_get_var MESHIP mesh_addr_ipv4 
json_get_var MESHBLOCK open_subnet_ipv4 
echo "recieved mesh IP:" $MESHIP >>$LOG
echo "recieved mesh block:" $MESHBLOCK"/26" >>$LOG

# complete rest of configurations in a reusable script
/opt/mesh/autoconf $MESHIP

# start some services
/etc/init.d/babeld start
/etc/init.d/meshrouting start

# remove cron job, set to reboot, and delete this script 
echo "deleting cronjob, removing /opt/mesh/retrieve_ip, and rebooting" >>$LOG
sed -i '/retrieve_ip/d' /etc/crontabs/root
reboot -d 10
rm -- "$0"
