#!/bin/sh

STATUS=$1
IFACE=$2

# TODO don't use ifconfig (it's deprecated)

case "$STATUS" in
  session.up)
    echo "Received 'session.up' for interface ${IFACE}"

    batctl if add $IFACE
    ifconfig $IFACE up

    ;;
  session.down)
    echo "Received 'session.down' for interface ${IFACE}"

    batctl if del $IFACE

    ;;
esac


