#!/bin/sh

uci set network.lan.ipaddr="172.22.0.1"
uci set network.lan.netmask="255.255.255.0"
uci set network.lan.proto="static"

uci set network.wan.ipaddr="172.22.1.1"
uci set network.wan.netmask="255.255.255.0"
uci set network.wan.proto="static"

uci commit network

exit 0
