#!/bin/sh
echo "Content-type: text/html"
echo

ip route

printf "\n ---\n\n"

iw dev priv5 station dump
iw dev open5 station dump
iw dev mesh5 station dump
iw dev priv2 station dump
iw dev open2 station dump
iw dev mesh2 station dump

printf "\n ---\n\n"

# see https://dev.openwrt.org/ticket/1203
cat /proc/net/arp

printf "\n ---\n\n"

swconfig dev eth0 show

printf "\n ---\n\n"

ip addr
